//
//  LoginInteractor.swift
//  DQHome
//
//  Created Ngoc Duong on 10/15/18.
//  Copyright © 2018 Engma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import AWSCognitoIdentityProvider

class LoginInteractor: LoginInteractorInputProtocol {
    
    func handleLogin(passwordAuthenticationCompletion: AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails>?, userName: String, password: String) {
        guard let _passwordAuthenticationCompletion = passwordAuthenticationCompletion else {
            print("Cannot login LoginViewController")
            NotificationCenter.default.post(name: Constants.LoginAgain, object: nil, userInfo: nil)
            return
        }
        
        let authDetails = AWSCognitoIdentityPasswordAuthenticationDetails(username: userName, password: password )
        _passwordAuthenticationCompletion.set(result: authDetails)
    }
    
    weak var presenter: LoginInteractorOutputProtocol?
}


