//
//  LoginPresenter.swift
//  DQHome
//
//  Created Ngoc Duong on 10/15/18.
//  Copyright © 2018 Engma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import AWSCognitoIdentityProvider

class LoginPresenter: LoginPresenterProtocol, LoginInteractorOutputProtocol {
    weak private var view: LoginViewProtocol?
    var interactor: LoginInteractorInputProtocol?
    private let router: LoginWireframeProtocol
    
    init(interface: LoginViewProtocol, interactor: LoginInteractorInputProtocol?, router: LoginWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func btnLoginTapped(passwordAuthenticationCompletion: AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails>?, userName: String, password: String) {
        if CognitoService.shared.token.isEmpty {
            interactor?.handleLogin(passwordAuthenticationCompletion: passwordAuthenticationCompletion, userName: userName, password: password)
        } else {
            goToHome()
        }
    }
    
    func goToHome() {
        router.goToHome()
    }
}
