//
//  LoginRouter.swift
//  DQHome
//
//  Created Ngoc Duong on 10/15/18.
//  Copyright © 2018 Engma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginRouter: LoginWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> LoginViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LoginViewController.initFrom(storyboardName: ConstantStoryboard.user)
        let interactor = LoginInteractor()
        
        let router = LoginRouter()
        let presenter = LoginPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func goToHome() {
        RouterService.shared.goToHome()
    }
}
