//
//  HomeViewController.swift
//  DQHome
//
//  Created Ngoc Duong on 10/18/18.
//  Copyright © 2018 Engma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

protocol HomeViewControllerDelegate: class {
    func itemHomeSelected(items: [Any], index: Int)
}

class HomeViewController: BaseViewController, HomeViewProtocol {
    
	var presenter: HomePresenterProtocol?
    @IBOutlet weak var cvHome: UICollectionView!
    weak var delegate: HomeViewControllerDelegate?
    
    var listItemHome = [Any]() {
        didSet {
            cvHome.reloadData()
        }
    }
    
	override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.viewDidLoad()
        
    }
    
    override func setUpViews() {
        super.setUpViews()
        configureCollection()
    }

}

// MARK: receive data
extension HomeViewController {
    func didGetHomeItems(items: [Any]) {
        listItemHome = items
    }
}

extension HomeViewController: UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    func configureCollection() {
        cvHome.dataSource = self
        cvHome.delegate = self
        cvHome.registerXibFile(HomeCell.self)
        
        if let layout = cvHome.collectionViewLayout as? UICollectionViewFlowLayout {
            layout.minimumLineSpacing = 2
            layout.minimumInteritemSpacing = 2
        }
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 0//listItemHome.count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = cvHome.dequeue(HomeCell.self, for: indexPath)
        cell.item = listItemHome[indexPath.item]
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        // get all room 
        delegate?.itemHomeSelected(items: listItemHome, index: indexPath.item)
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        
        let width = (cvHome.frame.width - 4 ) / 3
        
        return CGSize(width: width, height: width)
    }
    
    
}
