//
//  HomeInteractor.swift
//  DQHome
//
//  Created Ngoc Duong on 10/18/18.
//  Copyright © 2018 Engma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeInteractor: HomeInteractorInputProtocol {
    func getHomeItems() {
//        var listRoom = [GroupEntity]()
//        let newImageRoom1 = ImageRoom(svgUrl: "Room11")
//        let newImageRoom2 = ImageRoom(svgUrl: "Room12")
////        let newImageRoom3 = ImageRoom(svgUrl: "Room21")
//        let listImage = [newImageRoom1, newImageRoom2]
//        let newRoom = GroupEntity(name: "Phòng Demo 1", listImageRoom: listImage)
//        listRoom.append(newRoom)
//        
//        // Room 2
//        let newImageRoom21 = ImageRoom(svgUrl: "Room21")
//        let newImageRoom22 = ImageRoom(svgUrl: "Room22")
//        let listImage2 = [newImageRoom21, newImageRoom22]
//        let newRoom2 = GroupEntity(name: "Phòng Demo 2", listImageRoom: listImage2)
//        listRoom.append(newRoom2)
//        
        presenter?.didGetHomeItems(items: [])
    }

    weak var presenter: HomeInteractorOutputProtocol?
}
