//
//  ListRoomPresenter.swift
//  DQHome
//
//  Created Ngoc Duong on 10/30/18.
//  Copyright © 2018 Engma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ListGroupPresenter: ListGroupPresenterProtocol, ListGroupInteractorOutputProtocol {
    func groupSelected(group: GroupEntity) {
        interactor?.groupSelected(group: group)
    }
    
    func didGetTopGroup(groups: [GroupEntity]) {
        view?.didGetTopGroup(groups: groups)
    }
    
    func viewDidLoad() {
        interactor?.getTopGroup()
    }

    weak private var view: ListGroupViewProtocol?
    var interactor: ListGroupInteractorInputProtocol?
    private let router: ListGroupWireframeProtocol

    init(interface: ListGroupViewProtocol, interactor: ListGroupInteractorInputProtocol?, router: ListGroupWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
