//
//  ListSceneProtocols.swift
//  DQHome
//
//  Created Ngoc Duong on 10/30/18.
//  Copyright © 2018 Engma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ListSceneWireframeProtocol: class {

}
//MARK: Presenter -
protocol ListScenePresenterProtocol: class {

    var interactor: ListSceneInteractorInputProtocol? { get set }
    func viewDidLoad()
    func cellTapped(scene: SceneEntity)
}

//MARK: Interactor -
protocol ListSceneInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didGetScene(scenes: [SceneEntity])
}

protocol ListSceneInteractorInputProtocol: class {

    var presenter: ListSceneInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getScene()
    func sendSignalScene(scene: SceneEntity)
}

//MARK: View -
protocol ListSceneViewProtocol: class {

    var presenter: ListScenePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetScene(scenes: [SceneEntity])
}
