//
//  RightMenuRouter.swift
//  DQHome
//
//  Created Ngoc Duong on 10/22/18.
//  Copyright © 2018 Engma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RightMenuRouter: RightMenuWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = RightMenuViewController.initFrom(storyboardName: ConstantStoryboard.main)
        let interactor = RightMenuInteractor()
        let router = RightMenuRouter()
        let presenter = RightMenuPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
