//
//  RightMenuPresenter.swift
//  DQHome
//
//  Created Ngoc Duong on 10/22/18.
//  Copyright © 2018 Engma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RightMenuPresenter: RightMenuPresenterProtocol, RightMenuInteractorOutputProtocol {
    func didCreatedItemMenu(listItem: [Any]) {
        view?.didCreatedItemMenu(listItem: listItem)
    }
    
    func viewDidLoad() {
        interactor?.createItemMenu()
    }
    

    weak private var view: RightMenuViewProtocol?
    var interactor: RightMenuInteractorInputProtocol?
    private let router: RightMenuWireframeProtocol

    init(interface: RightMenuViewProtocol, interactor: RightMenuInteractorInputProtocol?, router: RightMenuWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
