//
//  RightMenuProtocols.swift
//  DQHome
//
//  Created Ngoc Duong on 10/22/18.
//  Copyright © 2018 Engma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol RightMenuWireframeProtocol: class {

}
//MARK: Presenter -
protocol RightMenuPresenterProtocol: class {

    var interactor: RightMenuInteractorInputProtocol? { get set }
    func viewDidLoad()
}

//MARK: Interactor -
protocol RightMenuInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didCreatedItemMenu(listItem: [Any])
}

protocol RightMenuInteractorInputProtocol: class {

    var presenter: RightMenuInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func createItemMenu()
}

//MARK: View -
protocol RightMenuViewProtocol: class {

    var presenter: RightMenuPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didCreatedItemMenu(listItem: [Any])
}
