//
//  LeftMenuRouter.swift
//  DQHome
//
//  Created Ngoc Duong on 10/22/18.
//  Copyright © 2018 Engma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LeftMenuRouter: LeftMenuWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> LeftMenuViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LeftMenuViewController.initFrom(storyboardName: ConstantStoryboard.main)
        let interactor = LeftMenuInteractor()
        let router = LeftMenuRouter()
        let presenter = LeftMenuPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
