//
//  LeftMenuViewController.swift
//  DQHome
//
//  Created Ngoc Duong on 10/22/18.
//  Copyright © 2018 Engma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

protocol LeftMenuViewControllerDelegate: class {
    func itemLeftMenuSelected(item: Any)
}

class LeftMenuViewController: UIViewController, LeftMenuViewProtocol {
    func didCreatedItemMenu(listItem: [Any]) {
        self.listItem = listItem
    }
    

	var presenter: LeftMenuPresenterProtocol?
    @IBOutlet weak var tbMenu: UITableView!
    weak var delegate: LeftMenuViewControllerDelegate?
    
    var listItem = [Any]() {
        didSet {
            tbMenu.reloadData()
        }
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        self.view.backgroundColor = AppColor.backgroundMenu
        presenter?.viewDidLoad()
        configureTable()
    }
}

extension LeftMenuViewController: UITableViewDelegate, UITableViewDataSource {
    func configureTable() {
        tbMenu.delegate = self
        tbMenu.dataSource  = self
        tbMenu.registerXibFile(HeaderLeftMenuCell.self)
        tbMenu.registerXibFile(LeftMenuCell.self)
        tbMenu.backgroundColor  = .clear
        tbMenu.separatorStyle = .none
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return listItem.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if indexPath.item == 0 {
            let cell = tbMenu.dequeue(HeaderLeftMenuCell.self, for: indexPath)
            
            return cell
        } else {
            let cell = tbMenu.dequeue(LeftMenuCell.self, for: indexPath)
            cell.itemMenu = listItem[indexPath.item]
            
            return cell
        }
        
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        delegate?.itemLeftMenuSelected(item: self.listItem[indexPath.item])
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return indexPath.item == 0 ? 80: 35
    }
}
