//
//  LeftMenuInteractor.swift
//  DQHome
//
//  Created Ngoc Duong on 10/22/18.
//  Copyright © 2018 Engma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

enum MenuType: String {
    case home = "Trang Chủ"
    case room = "Phòng"
    case scene = "Ngữ Cảnh"
    case logout = "Đăng xuất"
}

class LeftMenuInteractor: LeftMenuInteractorInputProtocol {
    func createItemMenu() {
        let itemMenu = [MenuType.home, MenuType.room, MenuType.scene, MenuType.logout]
        presenter?.didCreatedItemMenu(listItem: itemMenu)
    }
    
    weak var presenter: LeftMenuInteractorOutputProtocol?
}
